import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import "react-quill/dist/quill.snow.css";
import { Toaster } from "sonner";
import { QueryClientProvider } from "@/components/provider/QueryClientProvider";
import AuthSessionProvider from "@/components/provider/AuthSessionProvider";
import NextTopLoader from 'nextjs-toploader';

type FaviconResponse = {
  data?:
    | Array<{
        image?: string;
      }>
    | {
        image?: string;
      }
    | null;
};

const FALLBACK_FAVICON = "/fav1.png";

const getApiBase = () =>
  (process.env.NEXT_PUBLIC_API_BASE_URL ?? process.env.NEXT_PUBLIC_BACKEND_API_URL ?? "").replace(
    /\/+$/,
    ""
  );

const getRequestOrigin = () => {
  const headerStore = headers();
  const host = headerStore.get("x-forwarded-host") ?? headerStore.get("host");
  if (!host) return "";

  const protocol = headerStore.get("x-forwarded-proto") ?? "http";
  return `${protocol}://${host}`;
};

const getFaviconEndpoint = (origin = "") => {
  const base = getApiBase();
  if (!base) return origin ? `${origin}/api/v1/favicon` : "/api/v1/favicon";
  return base.endsWith("/api/v1") ? `${base}/favicon` : `${base}/api/v1/favicon`;
};

const fetchFavicon = async () => {
  try {
    const response = await fetch(getFaviconEndpoint(getRequestOrigin()), { cache: "no-store" });
    if (!response.ok) return FALLBACK_FAVICON;

    const payload = (await response.json()) as FaviconResponse;
    const favicon = Array.isArray(payload?.data) ? payload.data[0] : payload?.data;
    const imageUrl = typeof favicon?.image === "string" ? favicon.image.trim() : "";

    return imageUrl || FALLBACK_FAVICON;
  } catch {
    return FALLBACK_FAVICON;
  }
};

// Load Outfit from Google Fonts
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-outfit",
});

export async function generateMetadata(): Promise<Metadata> {
  const favicon = await fetchFavicon();

  return {
    title: "Yolo Heat Admin Dashboard",
    description: "Generated by create next app",
    icons: {
      icon: favicon,
    },
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-[#F0F3F6]`}>
        <NextTopLoader color="#FFDE59" height={3} showSpinner={false} />
        <QueryClientProvider>
          <Toaster richColors position="top-right" />
          <AuthSessionProvider>
            {children}
          </AuthSessionProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
