import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import "react-quill/dist/quill.snow.css";
import { Toaster } from "sonner";
import { QueryClientProvider } from "@/components/provider/QueryClientProvider";
import AuthSessionProvider from "@/components/provider/AuthSessionProvider";
import NextTopLoader from 'nextjs-toploader';

// Load Outfit from Google Fonts
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Yolo Heat Admin Dashboard",
  description: "Generated by create next app",
  icons: {
    icon: "/fav1.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-[#F0F3F6]`}>
        <NextTopLoader color="#FFDE59" height={3} showSpinner={false} />
        <QueryClientProvider>
          <Toaster richColors position="top-right" />
          <AuthSessionProvider>
            {children}
          </AuthSessionProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
