import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { QueryClientProvider } from "@/components/provider/QueryClientProvider";
import AuthSessionProvider from "@/components/provider/AuthSessionProvider";
import NextTopLoader from 'nextjs-toploader'

// Load Poppins from Google Fonts
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <NextTopLoader color="#FFDE59" height={3} showSpinner={false} />
        <QueryClientProvider>
          <Toaster richColors position="top-right" />
          <AuthSessionProvider>
            {children}
          </AuthSessionProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
